// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5oJmMcFSGzXMW8W324ihJ099mpudUbQ',
    appId: '1:120502007554:web:379d31159dca1221aef41b',
    messagingSenderId: '120502007554',
    projectId: 'gpsproject-ddea9',
    authDomain: 'gpsproject-ddea9.firebaseapp.com',
    storageBucket: 'gpsproject-ddea9.firebasestorage.app',
    measurementId: 'G-ZHN02KNSNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BjXJVi7u7KNigAIznDcnQi6nhzKNrUs',
    appId: '1:120502007554:android:954a60ac8f70f11caef41b',
    messagingSenderId: '120502007554',
    projectId: 'gpsproject-ddea9',
    storageBucket: 'gpsproject-ddea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5iAhiABipUwzg1R4D_MJYuv7S1ZNYpA',
    appId: '1:120502007554:ios:60baf23c9e145fb4aef41b',
    messagingSenderId: '120502007554',
    projectId: 'gpsproject-ddea9',
    storageBucket: 'gpsproject-ddea9.firebasestorage.app',
    iosBundleId: 'com.example.gps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5iAhiABipUwzg1R4D_MJYuv7S1ZNYpA',
    appId: '1:120502007554:ios:60baf23c9e145fb4aef41b',
    messagingSenderId: '120502007554',
    projectId: 'gpsproject-ddea9',
    storageBucket: 'gpsproject-ddea9.firebasestorage.app',
    iosBundleId: 'com.example.gps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS5oJmMcFSGzXMW8W324ihJ099mpudUbQ',
    appId: '1:120502007554:web:676007bbaa2abb8caef41b',
    messagingSenderId: '120502007554',
    projectId: 'gpsproject-ddea9',
    authDomain: 'gpsproject-ddea9.firebaseapp.com',
    storageBucket: 'gpsproject-ddea9.firebasestorage.app',
    measurementId: 'G-GVK404PBF0',
  );
}
