name: gps
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  location: ^8.0.1
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  permission_handler: ^12.0.1
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
